on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install nix 2.3.6
      uses: cachix/install-nix-action@v19
      with:
        install_url: https://releases.nixos.org/nix/nix-2.3.6/install
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Use maker cachix
      uses: cachix/cachix-action@v12
      with:
        name: maker

    - name: Run tests
      run: nix-shell --pure --run 'dapp test'
